// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Promo.EverythingIsNew.WebApp")]
[assembly: AssemblyCompanyAttribute("AltLanDS")]
[assembly: AssemblyCopyrightAttribute("Copyright © AltLanDS 2012-2015")]
[assembly: AssemblyVersionAttribute("1.2.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0.43")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.0";
    }
}
